services:
  patient-service:
    build:
      context: .
      dockerfile: patient-service/Dockerfile
    image: patient-service:latest
    container_name: patient-service
    env_file:
      - ./patient-service/.env
    ports:
      - "4000:4000"
    networks:
      - internal
    depends_on:
      - patient-service-db
      - billing-service

  billing-service:
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    image: billing-service:latest
    container_name: billing-service
    env_file:
      - ./billing-service/.env
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - internal

  patient-service-db:
    image: postgres:18
    ports:
      - "5001:5432"
    container_name: patient-service-db
    env_file:
      - ./patient-service/.env
    volumes:
      - ./db_volumes/patient-service-db:/var/lib/postgresql
    networks:
      - internal

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - internal
    depends_on:
      - patient-service-db

networks:
  internal:
    name: internal

#  A Dockerfile tells Docker how to build an image.
#  Your Compose file tells Docker how to run containers