server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # REST-CLIENT -> http://localhost:4004/api/v1/patients
            # API-GATEWAY -> http://patient-service:4000/api/v1/patients
            # PATIENT-SERVICE (SPRING BOOT APP) -> api/v1/patients -> Patients array
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates: # what requests get sent to patient service
                - Path=/api/v1/patients, /api/v1/patients/**

            # REST-CLIENT -> http://localhost:4004/api/v1/patients
            # API-GATEWAY -> http://patient-service:4000/v3/api-docs
            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/docs/patients
              filters:
                - RewritePath=/api/docs/patients,/v3/api-docs


