spring.application.name=patient-service

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:postgresql://patient-service-db:5001/${POSTGRES_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# jpa to sync the entities with the database
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

server.port=4000

# we want all info, warn and error messages logged to the terminal
logging.level.root=info 
